apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-withdrawal
  labels:
    app: service-withdrawal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-withdrawal
  template:
    metadata:
      labels:
        app: service-withdrawal
    spec:
      containers:
      - name: app-withdrawal
        image: stivid007/nodejs-withdrawal:1
        ports:
        - containerPort: 5004
        env:
        - name: NACOS_SERVERADDR
          value: "164.90.255.230:8848"
        - name: NACOS_NAMESPACE
          value: "aforo255"
        - name: NACOS_IDENTITYKEY
          value: "nacos"
        - name: NACOS_IDENTITYVALUE
          value: "nacos"
        - name: NACOS_ENV
          value: "PROD"
---
kind: Service
apiVersion: v1
metadata:
  name: app-service-withdrawal
spec:
  type: LoadBalancer
  selector:
    app: service-withdrawal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5004
    name: http